apm install atom-beautify
apm install atom-json-color
apm install autocomplete-bash-builtins
apm install autocomplete-python
apm install emmet
apm install file-icons
apm install git-plus
apm install minimap
apm install pretty-json
apm install python-autopep8
apm install python-debugger
apm install python-indent
